services:
  - type: web
    name: enejistats-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://enejistats:enejiPass123%21@enejistats.o63uxvq.mongodb.net/enejistats?retryWrites=true&w=majority&appName=Enejistats
      - key: SECRET_KEY
      
